from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path

from quant_research_platform.config import QuantPlatformConfig
from quant_research_platform.data import fetch_openbb_ohlcv, save_ohlcv_csv
from quant_research_platform.hybrid import run_tw_hybrid
from quant_research_platform.qlib_adapter import build_qlib_signal_backtest_config
from quant_research_platform.twse_realtime import (
    fetch_full_market_universe,
    load_universe_channels,
    poll_realtime_quotes,
    save_universe_csv,
)
from quant_research_platform.workflow import run_quant_workflow


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the integrated quant research platform.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    run_parser = subparsers.add_parser("run", help="Run data, signal, portfolio, and report workflow.")
    run_parser.add_argument("--config", required=True, help="Path to quant platform JSON config.")
    run_parser.add_argument("--date", help="Report date in YYYY-MM-DD.")

    twse_parser = subparsers.add_parser("poll-twse-realtime", help="Poll TWSE MIS realtime quotes into cache CSV.")
    twse_parser.add_argument("--symbols", nargs="+", default=(), help="Symbols or channels, e.g. 2330 2454 otc:6488.")
    twse_parser.add_argument("--symbols-file", help="Text file with one symbol or channel per line.")
    twse_parser.add_argument("--universe-csv", help="Universe CSV with a channel column.")
    twse_parser.add_argument("--full-market", action="store_true", help="Fetch listed and OTC universe before polling.")
    twse_parser.add_argument("--common-stock-only", action="store_true", help="Limit full-market universe to 4-digit common stocks.")
    twse_parser.add_argument("--cache", default="data/twse_realtime_cache.csv", help="Output cache CSV path.")
    twse_parser.add_argument("--interval", type=float, default=10.0, help="Seconds between polling rounds.")
    twse_parser.add_argument("--batch-size", type=int, default=75, help="Symbols per request, recommended 50-100.")
    twse_parser.add_argument("--iterations", type=int, help="Polling rounds. Omit to run until interrupted.")
    twse_parser.add_argument("--default-market", default="tse", choices=["tse", "otc"], help="Market for bare symbols.")
    twse_parser.add_argument("--sleep-min", type=float, default=0.2, help="Minimum random sleep between batches.")
    twse_parser.add_argument("--sleep-max", type=float, default=1.2, help="Maximum random sleep between batches.")

    universe_parser = subparsers.add_parser("fetch-twse-universe", help="Fetch full TWSE listed and TPEx OTC universe.")
    universe_parser.add_argument("--output", default="data/twse_realtime_universe.csv", help="Universe CSV output path.")
    universe_parser.add_argument("--common-stock-only", action="store_true", help="Limit to 4-digit common stocks.")

    openbb_parser = subparsers.add_parser("fetch-openbb-us", help="Fetch US OHLCV data through OpenBB and cache to CSV.")
    openbb_parser.add_argument("--symbols", nargs="+", required=True, help="US symbols, e.g. AAPL MSFT NVDA.")
    openbb_parser.add_argument("--output", default="data/openbb_us_ohlcv.csv", help="OHLCV CSV output path.")
    openbb_parser.add_argument("--provider", help="Optional OpenBB provider.")
    openbb_parser.add_argument("--period", default="1y", help="Fallback yfinance period when OpenBB provider fails.")

    ohlcv_parser = subparsers.add_parser("fetch-yahoo-ohlcv", help="Fetch OHLCV data through OpenBB/Yahoo and cache to CSV.")
    ohlcv_parser.add_argument("--symbols", nargs="+", required=True, help="Symbols, e.g. 2330.TW 6488.TWO AAPL.")
    ohlcv_parser.add_argument("--output", required=True, help="OHLCV CSV output path.")
    ohlcv_parser.add_argument("--provider", default="yfinance", help="Optional OpenBB provider.")
    ohlcv_parser.add_argument("--period", default="1y", help="Fallback Yahoo period.")

    qlib_parser = subparsers.add_parser("prepare-qlib-backtest", help="Create a Qlib signal backtest scaffold config.")
    qlib_parser.add_argument("--signal-csv", required=True, help="Signal CSV generated by the quant platform.")
    qlib_parser.add_argument("--output", default="configs/qlib_signal_backtest.yaml", help="Output YAML path.")
    qlib_parser.add_argument("--market", default="custom_tw", help="Qlib market/data folder name.")
    qlib_parser.add_argument("--benchmark", default="SH000300", help="Benchmark instrument.")
    qlib_parser.add_argument("--topk", type=int, default=50)
    qlib_parser.add_argument("--n-drop", type=int, default=5)

    hybrid_parser = subparsers.add_parser("run-tw-hybrid", help="Run TW hybrid scoring with Kronos, Daily Stock Analysis, MIS, and Qlib handoff.")
    hybrid_parser.add_argument("--config", default="configs/quant_platform.tw.example.json")
    hybrid_parser.add_argument("--date", help="Report date in YYYY-MM-DD.")
    hybrid_parser.add_argument("--realtime-cache", default="data/twse_common_stock_realtime_cache.csv")
    hybrid_parser.add_argument("--news-path", default="data/news_rss.csv")
    hybrid_parser.add_argument("--rss-sources", help="Optional RSS sources JSON; fetches fresh RSS when provided.")
    hybrid_parser.add_argument("--notify", action="store_true")
    hybrid_parser.add_argument("--webhook-env")
    hybrid_parser.add_argument("--line-token-env", default="LINE_CHANNEL_ACCESS_TOKEN")
    hybrid_parser.add_argument("--line-to-env")
    hybrid_parser.add_argument("--line-broadcast", action="store_true")

    args = parser.parse_args()
    if args.command == "run":
        config = QuantPlatformConfig.from_file(args.config)
        result = run_quant_workflow(config, date.fromisoformat(args.date) if args.date else None)
        print(f"report_path={result.report_path}")
        print(f"signal_csv_path={result.signal_csv_path}")
        print(f"qlib_handoff_path={result.qlib_handoff_path}")
        print(f"signals={len(result.signals)}")
        print(f"positions={len(result.backtest.selected)}")
        print(f"net_expected_return={result.backtest.net_expected_return:.6f}")
    elif args.command == "poll-twse-realtime":
        symbols = list(args.symbols)
        if args.symbols_file:
            symbols.extend(_read_symbol_file(Path(args.symbols_file)))
        if args.universe_csv:
            symbols.extend(load_universe_channels(Path(args.universe_csv)))
        if args.full_market:
            universe_path = Path(args.universe_csv or "data/twse_realtime_universe.csv")
            universe = fetch_full_market_universe(common_stock_only=args.common_stock_only)
            save_universe_csv(universe_path, universe)
            symbols.extend(item.channel for item in universe)
        if not symbols:
            raise SystemExit("--symbols, --symbols-file, --universe-csv, or --full-market is required.")
        poll_realtime_quotes(
            symbols,
            cache_path=Path(args.cache),
            interval_seconds=args.interval,
            batch_size=args.batch_size,
            iterations=args.iterations,
            default_market=args.default_market,
            random_sleep_min=args.sleep_min,
            random_sleep_max=args.sleep_max,
        )
        print(f"cache_path={args.cache}")
    elif args.command == "fetch-twse-universe":
        universe = fetch_full_market_universe(common_stock_only=args.common_stock_only)
        output = save_universe_csv(Path(args.output), universe)
        print(f"universe_path={output}")
        print(f"symbols={len(universe)}")
    elif args.command == "fetch-openbb-us":
        bars_by_symbol = fetch_openbb_ohlcv(args.symbols, args.provider, args.period)
        output = save_ohlcv_csv(Path(args.output), bars_by_symbol)
        rows = sum(len(rows) for rows in bars_by_symbol.values())
        print(f"output={output}")
        print(f"symbols={len(bars_by_symbol)}")
        print(f"rows={rows}")
    elif args.command == "fetch-yahoo-ohlcv":
        bars_by_symbol = fetch_openbb_ohlcv(args.symbols, args.provider, args.period)
        output = save_ohlcv_csv(Path(args.output), bars_by_symbol)
        rows = sum(len(rows) for rows in bars_by_symbol.values())
        print(f"output={output}")
        print(f"symbols={len(bars_by_symbol)}")
        print(f"rows={rows}")
    elif args.command == "prepare-qlib-backtest":
        output = build_qlib_signal_backtest_config(
            signal_csv=Path(args.signal_csv),
            market=args.market,
            benchmark=args.benchmark,
            output_path=Path(args.output),
            topk=args.topk,
            n_drop=args.n_drop,
        )
        print(f"qlib_config={output}")
    elif args.command == "run-tw-hybrid":
        config = QuantPlatformConfig.from_file(args.config)
        report_date = date.fromisoformat(args.date) if args.date else date.today()
        report_path, csv_path, qlib_path, notification = run_tw_hybrid(
            config,
            report_date,
            realtime_cache=Path(args.realtime_cache) if args.realtime_cache else None,
            news_path=Path(args.news_path) if args.news_path else None,
            rss_sources_path=Path(args.rss_sources) if args.rss_sources else None,
            notify=args.notify,
            webhook_env=args.webhook_env,
            line_channel_access_token_env=args.line_token_env,
            line_to_env=args.line_to_env,
            line_broadcast=args.line_broadcast,
        )
        print(f"report_path={report_path}")
        print(f"csv_path={csv_path}")
        print(f"qlib_config={qlib_path}")
        print(f"notification={notification}")


def _read_symbol_file(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


if __name__ == "__main__":
    main()
